;
; *************************************
; *                                   *
; * INITIALISATION DU SYSTEME XWINDOW *
; *                                   *
; *************************************
;
;
Declare.l XWindow_InitializeSkin()
DeclareCDLL.l XWindow_Initialize( SkinO.l )
DeclareCDLL XWindow_ClearSystem()
DeclareCDLL XWindow_TrueCloseMode()
DeclareCDLL XWindow_FakeCloseMode()
DeclareCDLL XWindow_EnableAlphaiser()
DeclareCDLL XWindow_DisableAlphaiser()
Declare XWindow_SetupAlphaiserInternal()
DeclareCDLL XWindow_Create( WinNum.l , XSize.l , YSize.l )
DeclareCDLL XWindow_SetChatWin( WinNum.l )
DeclareCDLL XWindow_DisableChatwin()
DeclareCDLL XWindow_Alpha( WinNum.l , Alpha.l )
DeclareCDLL XWindow_ToBack( WinNum.l )
DeclareCDLL XWindow_ToFront( WinNum.l )
DeclareCDLL XWindow_Position( WinNum.l , Xpos.l , Ypos.l )
DeclareCDLL XWindow_Properties( WinNum.l , Borders.l , Title.l , Draggeable.l , Close.l )
DeclareCDLL XWindow_SetBorderOff( WinNum.l )
DeclareCDLL XWindow_SetBorderOn( WinNum.l )
DeclareCDLL XWindow_SetTitleOff( WinNum.l )
DeclareCDLL XWindow_SetTitleOn( WinNum.l )
DeclareCDLL XWindow_SetDraggingOff( WinNum.l )
DeclareCDLL XWindow_SetDraggingOn( WinNum.l )
DeclareCDLL XWindow_SetCloseOff( WinNum.l )
DeclareCDLL XWindow_SetCloseOn( WinNum.l )
DeclareCDLL XWindow_Title( WinNum.l , NewTitle.l )
DeclareCDLL XWindow_Delete( WinNum.l )
DeclareCDLL XWindow_Show( WinNum.l )
DeclareCDLL XWindow_Hide( WinNum.l )
DeclareCDLL.l GetWindowVisible( WinNum.l )
Declare.l XWindow_XLimit( Winnum.l )
Declare.l XWindow_XMin( Winnum.l )
Declare.l XWindow_YLimit( Winnum.l )
Declare.l XWindow_YMin( Winnum.l )
Declare XWindow_RepositionAttached( WinNum.l )
DeclareCDLL XWindow_Refresh()
Declare XWindow_RefreshInternal( WinNum.l )
Declare XWindow_GetWindowInternal()
DeclareCDLL.l XWindow_GetCurrentWindow()
DeclareCDLL.l XWindow_GetWinXPos( WinNum.l )
DeclareCDLL.l XWindow_GetWinYPos( WinNum.l )
DeclareCDLL.l XWindow_Exist( WinNum.l )
DeclareCDLL XWindow_Stretch( WinNum.l , XSize.l , YSize.l )
DeclareCDLL XWindow_DefaultSize( WinNum.l )
DeclareCDLL XWindow_UseXFont( WinNum.l , FontNumber.l )
DeclareCDLL XWindow_DefaultFont( WinNum.l )
DeclareCDLL.l XWindow_GetFreeWindow()
DeclareCDLL.l XGui_UseMipMap( Mode.l )
;
DeclareCDLL XWindow_AddGadget( WinNum.l , GadNum.l , Xpos.l , Ypos.l , XSize.l , Ysize.l , Imag.l )
DeclareCDLL XWindow_AddGadgetCombination( WinNum.l , GadNum.l , Xpos.l , Ypos.l , XSize.l , Ysize.l , Imag.l , Texto.l )
DeclareCDLL XWindow_AddGadgetTexte( WinNum.l , GadNum.l , Xpos.l , Ypos.l , XSize.l , Ysize.l , Texto.l )
Declare XWindow_GadgetAdaptInternal( GadNum.l )
Declare XWindow_GadgetRefreshFast( GadNum.l )
DeclareCDLL XWindow_DeleteGadget( GadNum.l )
DeclareCDLL.l XWindow_GetCurrentGadget()
DeclareCDLL XWindow_SetGadgetImage( GadNum.l , Imag.l )
Declare XWindow_SetGadgetTextInternal( GadNum.l , Texte$ )
DeclareCDLL XWindow_SetGadgetText( GadNum.l , Texto.l )
DeclareCDLL XWindow_PositionGadget( GadNum.l , XPos.l , YPos.l )
;
DeclareCDLL XFont_SetupFont( ImageFile.l , FontNumber.l , FontSize.l , FirstChar.l , Flag.l )
DeclareCDLL XFont_ClearFont( FontNumber )
DeclareCDLL XFont_ClearAllFont()
DeclareCDLL.l XFont_Exist( FontNumber.l )
DeclareCDLL XFont_SetCursor( XCursor.l , YCursor.l )
DeclareCDLL XFont_SetCurrentFont( FontNumber.l )
Declare.l XFont_GetTextWidthInternal( Texte$ )
DeclareCDLL.l XFont_GetTextWidth( Texto.l )
Declare.l XFont_GetTextHeightInternal( Texte$ )
DeclareCDLL.l XFont_GetTextHeight( Texto.l )
Declare XFont_PrintFast( Texte$ )
Declare XFont_GadgetPrintFast( Texte$ )
DeclareCDLL XFont_Print( Texto.l )
DeclareCDLL XFont_SetCurrentBitmap( Btmp.l )
DeclareCDLL XWindow_AttachWindow( MasterWin.l , TargetWin.l , Position.l )
DeclareCDLL XWindow_DetachWindow( TargetWin.l )
DeclareCDLL.l XWindow_GetAttached( WinNum.l )
DeclareCDLL XWindow_SetTextOpaque()
DeclareCDLL XWindow_SetTextTransparent()
DeclareCDLL.l XWindow_GetWinGadgetCount( WinNum.l )
DeclareCDLL XWindow_SetChatGadget( GadNum.l )
DeclareCDLL XWindow_SetChatWindowGadget( GadNum.l )
Declare XWindow_TalkToChatInternal( TEXTE$ )
DeclareCDLL XWindow_TalkToChat( Texto.l )
DeclareCDLL XWindow_SetChatScanCode( Key.l )
DeclareCDLL.l XWindow_ChatReadingKey()
DeclareCDLL.l XWindow_GetLastCommand( Teste.l )
DeclareCDLL XFont_AutoReturnMode( Mode.l )

; IDE Options = PureBasic 4.20 (Windows - x86)
; CursorPosition = 95
; FirstLine = 39
; Folding = -